### ISSUE TITLE
Tokens occasionally one time use?

### ISSUE THREAD

**Issue by harrypropellernet** [hozn/stravalib#143]
More often than not the tokens I have collected work the first time then will return bad requests if you try to run them again? Is this by design by strava?
``
Traceback (most recent call last):
  File "C:/Users/HarryAdams/PycharmProjects/EvansCycles/main.py", line 17, in <module>
    access_token = client.exchange_code_for_token(client_id=removed, client_secret='clientsecretremoved', code='tokennumberremoved')
  File "C:\Users\HarryAdams\PycharmProjects\EvansCycles\venv\lib\site-packages\stravalib\client.py", line 130, in exchange_code_for_token
    code=code)
  File "C:\Users\HarryAdams\PycharmProjects\EvansCycles\venv\lib\site-packages\stravalib\protocol.py", line 115, in exchange_code_for_token
    method='POST')
  File "C:\Users\HarryAdams\PycharmProjects\EvansCycles\venv\lib\site-packages\stravalib\protocol.py", line 174, in _request
    self._handle_protocol_error(raw)
  File "C:\Users\HarryAdams\PycharmProjects\EvansCycles\venv\lib\site-packages\stravalib\protocol.py", line 221, in _handle_protocol_error
    raise exc_class(msg, response=response)
stravalib.exc.Fault: 400 Client Error: Bad Request [Bad Request: [{'resource': 'RequestToken', 'field': 'code', 'code': 'invalid'}]]
``

**Comment by jsamoocha** [comment]
Yes, you only need to exchange a temporary code for a permanent access token once. From that moment on, you use the permanent access token to access the API on behalf of that user.
