### ISSUE TITLE
Error when calling get_athlete()

### ISSUE THREAD

**Issue by patfelst** [hozn/stravalib#156]
When I call "get_athlete()" I get this error, although the call is successful and returns data as expected.

`No such attribute subscription_permissions on entity <Athlete id=None firstname=None lastname=None>`

I've tried calling:
`stats = client.get_athlete_stats(athlete_id = strava_id)` (where strava_id is my id as an integer) but  python throws an exception (crashes) with the following message:

```
Traceback (most recent call last):
  File "strava.py", line 337, in <module>
    athlete_details = client.get_athlete(athlete_id = strava_id)
  File "/home/pi/strava_pyenv/lib/python3.5/site-packages/stravalib/client.py", line 212, in get_athlete
    raise NotImplementedError("The /athletes/{id} endpoint was removed by Strava.  "
NotImplementedError: The /athletes/{id} endpoint was removed by Strava.  See https://developers.strava.com/docs/january-2018-update/
```
Am I doing something wrong, or does the library need to be updated?

**Comment by hozn** [comment]
The first warning (not an error) just indicates that we do need to add a missing attribute to the model (Strava is constantly tweaking the structure of their models.)

The second exception is hopefully pretty clear from the message; this endpoint no longer exists.

**Comment by patfelst** [comment]
ok thanks, is there a way for me to suppress the warning so it doesn't display on my python console? Apologies, this is probably not a library question, but I'm new to python.

**Comment by hozn** [comment]
You could configure your logger to raise level to error for qualname=stravalib. But I can also fix that -- probably later today by adding the missing attribute.

(We should probably drop those to a lower log level too. It is useful to know when new attractive are added since they don't announce this on the dev list, but in most cases it won't affect existing functionality.)

**Comment by patfelst** [comment]
Sorry I misread your first reply. What is the missing attribute that needs to be added? Looking at the current API, it appears GET /athlete does not need any? What are these "subscription_permissions"?

And thanks again, I will also look into logger error reporting levels.

**Comment by hozn** [comment]
Yeah, no param is required, so:
```python
me = client.get_athlete()
```
is the correct call.

I'm looking now at this issue, though, and plan to push out a fix shortly to add this new attr (once I figure out what it actually is/contains).

**Comment by patfelst** [comment]
Much appreciated, thank you

**Comment by hozn** [comment]
Ok -- I uploaded a 0.9.3 that should not emit this warning.

**Comment by patfelst** [comment]
Great. I see it is not documented. Interesting...

How long does it take to get into pip?

**Comment by hozn** [comment]
Ok -- I was a little hasty, sorry :)  -- I uploaded 0.9.3 but forgot to do the changelog, and since twine won't let me name file same name, so it is 0.9.4 now :-)  You should see it there.

**Comment by patfelst** [comment]
Got 0.9.4 now and the warning has gone - thanks!

**Comment by hozn** [comment]
No prob -- thanks for pointing out the issue!
