### ISSUE TITLE
stravalib.exc.ObjectNotFound when trying client.update_activity()

### ISSUE THREAD

**Issue by ethanopp** [hozn/stravalib#186]
Does this function still work with v3 of strava API?

I've tried it with client authed both as `scope='profile:write'` and `scope='activity:write'` 

Getting the following when trying this simple call:
`    client.update_activity(activity_id=18638834,name='Test Name')
`

Error:
```Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Ethan/PycharmProjects/fitness/index.py", line 238, in <module>
    test()
  File "C:\Users\Ethan\PycharmProjects\fitness\pages\pandasTesting.py", line 13, in test
    client.update_activity(activity_id=18638834,name='Test Name')
  File "C:\Users\Ethan\PycharmProjects\fitness\venv\lib\site-packages\stravalib\client.py", line 644, in update_activity
    raw_activity = self.protocol.put('/activities/{activity_id}', activity_id=activity_id, **params)
  File "C:\Users\Ethan\PycharmProjects\fitness\venv\lib\site-packages\stravalib\protocol.py", line 317, in put
    return self._request(url, params=params, method='PUT', check_for_errors=check_for_errors, use_webhook_server=use_webhook_server)
  File "C:\Users\Ethan\PycharmProjects\fitness\venv\lib\site-packages\stravalib\protocol.py", line 221, in _request
    self._handle_protocol_error(raw)
  File "C:\Users\Ethan\PycharmProjects\fitness\venv\lib\site-packages\stravalib\protocol.py", line 268, in _handle_protocol_error
    raise exc_class(msg, response=response)
stravalib.exc.ObjectNotFound: Not Found: Record Not Found: [{'resource': 'Activity', 'field': 'id', 'code': 'invalid'}]
```

**Comment by ethanopp** [comment]
This was due to bad scope being passed... Fixed with the following:
`scope=['read', 'read_all', 'profile:read_all', 'profile:write', 'activity:read','activity:read_all', 'activity:write'])`
